DjangoWebsite/DjangoWebsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include("music.urls"))
]

DjangoWebsite/music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [

    # /music/
    url(r"^$",views.index, name="IndexPage"),

    # /music/712/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /music/<album_id>/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite,name='favorite'),

]

DjangoWebsite/music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.artist + " - " + self.album_title

class Songs(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

DjangoWebsite/music/views.py
from .models import Album, Songs
from django.shortcuts import render,get_object_or_404

def index(request):
    all_albums = Album.objects.all()
    return render(request,'music/index.html',{'all_albums' : all_albums})

def detail(request,album_id):
    '''try:
        album = Album.objects.get(pk = album_id)
    except Album.DoesNotExist:
        raise Http404("Album Does Not Exist")'''

    #instead of above code this can be used
    album = get_object_or_404(Album, pk=album_id)
    return render(request,'music/detail.html',{'album':album})

def favorite(request,album_id):
    album = get_object_or_404(Album,pk=album_id)
    try:
        selected_song = album.songs_set.get(pk = request.POST['song'])
    except (KeyError, Songs.DoesNotExist):
        return render(request, 'music/detail.html',{
            'album' : album,
            'error_message' : "You did not select a valid song",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request,'music/detail.html',{'album':album})

DjangoWebsite/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:IndexPage' %}">Viberr</a>
        </div>
    </div>

    <!--Items-->
    <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
            <li class="active">
                <a href="{% url 'music:IndexPage' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbspAlbums
                </a>
            </li>
            <li class="">
                <a href="#">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbspSongs
                </a>
            </li>
        </ul>

        <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="#">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                </a>
            </li>
            <li class="">
                <a href="#">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                </a>
            </li>
        </ul>

    </div>
</nav>
{% block body%}
{% endblock %}
</body>
</html>

DjangoWebsite/music/templates/music/detail.html

{% extends 'music/base.html' %}
{% block title%}Song Details{% endblock %}

{% block body%}
<img src="{{ album.album_logo }}" height="50%" width="40%">

<h1> {{ album.album_title }} </h1>
<h3> {{ album.artist }} </h3>

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.songs_set.all %}
        <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
        <label for="song{{forloop.counter}}">
            {{song.song_title}}
            {% if song.is_favorite %}
                <img src="https://i.imgur.com/b9b13Rd.png"/>
            {% endif %}
        </label></br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>
{% endblock %}

DjangoWebsite/music/templates/music/index.html
<!--Loads the path to static files-->

{% extends 'music/base.html' %}


{% block body%}
    {% if all_albums %}
        <h3>&nbsp; All Albums:</h3>
        <ul>
            {% for album in all_albums %}
                <li><a href = "{% url 'music:detail' album.id %}">{{album.album_title}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any albums</h3>
    {% endif %}
{% endblock %}